# This is a basic workflow to help you get started with Actions

name: github-terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENENT_ID }}
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash
    
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Terraform format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.10
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: "./terraform-bhs"
      
      - name: 'Terraform init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.10
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./terraform-bhs"
      
      - name: 'Terraform validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.10
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: "./terraform-bhs"

      - name: 'Terraform plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.10
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "./terraform-bhs"
      
      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.10
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./terraform-bhs"
