name: Terraform

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
      branches:
      - main
    pull_request:
    workflow_dispatch: 

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENENT_ID }}
  ROOT_PATH: ${{ github.workspace }}/terraform-bhs
  #ROOT_PATH: '../terraform-bhs'

jobs:
    terraform_plan:
      name: 'Terraform Plan Stage'
      runs-on: ubuntu-latest

      defaults:
        run:
          shell: bash
    
      steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          #terrform_version: 0.12.25
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.ROOT_PATH }}

      - name: terraform plan
        run: terraform plan
        working-directory: ${{ env.ROOT_PATH }}

    terraform_apply:
      name: 'Terraform Apply Stage'
      runs-on: ubuntu-latest
      needs: terraform_plan # needs keyword similar to depends_on 
      environment: demo

      defaults:
        run:
          shell: bash
    
      steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          #terrform_version: 0.12.25
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.ROOT_PATH }}

      - name: terraform apply
        run: terraform apply --auto-approve
        working-directory: ${{ env.ROOT_PATH }}
